name: CI

on:
  push:
    branches:
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        solr-version: [8.7]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: copy settings
        run: cp settings_travis.py settings.py
      - name: install requirements
        run: pip install pytest coveralls -r requirements.txt
      - name: run solr
        run: >
          docker run -d --rm -v "/var/run/docker.sock":"/var/run/docker.sock" \
            -v "${{ github.workspace }}/configsets/tapioca":"/opt/solr/server/solr/configsets/tapioca" \
            --network $(docker network ls --format="{{ .Name }}" --filter "Name=^github_network_") \
              solr:${{ matrix.solr-version }}
      - name: run coverage
        run: coverage run --source=opentapioca --omit="*/tests/*" -m py.test && coveralls